# Generated by Django 6.1.1 on 2026-10-05 16:31

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock in'), ('STOCK_OUT', 'Stock out'), ('ADJUSTMENT', 'Adjustment'), ('ORDER', 'Order'), ('RETURN', 'Return')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('transaction_type__in', ['STOCK_IN', 'STOCK_OUT', 'ADJUSTMENT', 'ORDER', 'RETURN'])), name='inventory_valid_type'), models.CheckConstraint(condition=models.Q(('new_stock', django.db.models.expressions.CombinedExpression(models.F('previous_stock'), '+', models.F('quantity')))), name='inventory_stock_matches_change')],
            },
        ),
    ]
